name: CI 

on:
  push:
   branches:
     - main

env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: password

jobs:
  run-tests:
    runs-on: ubuntu-latest 

    steps:
      - name: Sets Up MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'ALTER USER "${{env.DB_USER}}"@"localhost" IDENTIFIED BY "${{env.DB_PASSWORD}}";' -uroot -proot 
          sudo mysql -e 'CREATE DATABASE ${{env.DB_NAME}};' -u${{env.DB_USER}} -p${{env.DB_PASSWORD}} 

      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Linting
        run: |
          go fmt ./ ...
          go vet ./ ... 

      - name: Runs Tests
        run: |
          go test 
